// Reverses the javascript-obfuscator.io string-array encoding used in
// pokelike_forked/js/bundle.*.js, without executing any of the game logic.
//
// How the obfuscation works in this bundle:
//   - A giant array of literal strings is built once by a memoized
//     `function K(){ const arr=[...]; K=()=>arr; return K(); }`.
//   - A single real decoder `function k(idx, _){ idx -= 0x1d3; return K()[idx]; }`
//     looks up one entry by a shifted index.
//   - Every protected function opens with a local alias of the decoder,
//     e.g. `const Bn0 = Bm9;` where `Bm9` itself is `const Bm9 = k;` declared
//     elsewhere (often at the very top of the file) -- i.e. alias CHAINS,
//     not just direct `= k` bindings. Missing the transitive closure here
//     silently leaves whole functions un-decoded (calls like `Bn0(0x1ad4)`)
//     without throwing, which is easy to miss -- watch for this if the
//     bundle is regenerated by a newer obfuscator config.
//   - A one-time rotate step at the very top of the file (`(function(...){
//     ...}(K, 0x49402))`) reorders K()'s backing array at load time; it must
//     be executed (not skipped) before any k(idx) call, or every index
//     resolves to the wrong string.
//
// This script extracts K(), k(), and the rotate bootstrap verbatim via
// brace-balanced string slicing (no execution of anything else in the
// bundle), runs just those three pieces in a `vm` sandbox to get a working
// decoder, finds every local alias of k (transitively, since aliases alias
// aliases), and replaces every `alias(0xHEX)` call in the ENTIRE source with
// the literal decoded string. Local variable names (Bm9, B2O, iu, ...) are
// NOT renamed -- only the string-array lookups are resolved.
//
// Usage:
//   node decode-strings.js <input-bundle.js> <output-file.js>
//
// Then run `prettier --write <output-file.js>` (or any JS formatter) to get
// readable line-per-statement output before grepping/reading it.

const fs = require('fs');
const vm = require('vm');

const [, , inPath, outPath] = process.argv;
if (!inPath || !outPath) {
  console.error('Usage: node decode-strings.js <input-bundle.js> <output-file.js>');
  process.exit(1);
}

const src = fs.readFileSync(inPath, 'utf8');

function balanceFrom(s, idx) {
  const open = s[idx];
  const close = { '(': ')', '{': '}', '[': ']' }[open];
  let depth = 0, inString = null;
  for (let i = idx; i < s.length; i++) {
    const c = s[i];
    if (inString) {
      if (c === '\\') { i++; continue; }
      if (c === inString) inString = null;
      continue;
    }
    if (c === '"' || c === "'" || c === '`') { inString = c; continue; }
    if (c === open) depth++;
    else if (c === close) { depth--; if (depth === 0) return i + 1; }
  }
  throw new Error('unbalanced from ' + idx);
}

function extractFunctionDecl(s, fnIdx) {
  const parenIdx = s.indexOf('(', fnIdx);
  const afterParams = balanceFrom(s, parenIdx);
  const braceIdx = s.indexOf('{', afterParams);
  const afterBody = balanceFrom(s, braceIdx);
  return s.slice(fnIdx, afterBody);
}

// 1. The memoized array-returning function, e.g. `function K(){...}`.
const arrayFnMatch = src.match(/function ([A-Za-z_$][\w$]*)\(\)\{const [A-Za-z_$][\w$]*=\[/);
if (!arrayFnMatch) throw new Error('could not find the string-array function (function X(){const Y=[...')
const arrayFnName = arrayFnMatch[1];
const arrayFnSrc = extractFunctionDecl(src, arrayFnMatch.index);

// 2. The real decoder, e.g. `function k(B,O){B=B-0x1d3;const c=K();let I=c[B];return I;}`.
const decoderRe = new RegExp(`function ([A-Za-z_$][\\w$]*)\\([A-Za-z_$][\\w$]*,[A-Za-z_$][\\w$]*\\)\\{[A-Za-z_$][\\w$]*=[A-Za-z_$][\\w$]*-0x[0-9a-fA-F]+;const [A-Za-z_$][\\w$]*=${arrayFnName}\\(\\);`);
const decoderMatch = src.match(decoderRe);
if (!decoderMatch) throw new Error('could not find the decoder function referencing ' + arrayFnName + '()');
const decoderName = decoderMatch[1];
const decoderSrc = extractFunctionDecl(src, decoderMatch.index);

// 3. The one-time rotate bootstrap: `(function(a,b){...}(ARRAY_FN, CONST));`
//    (obfuscator.io wraps the whole call expression in one outer paren).
const bootMatch = src.match(new RegExp(`\\(function\\([A-Za-z_$][\\w$]*,[A-Za-z_$][\\w$]*\\)\\{`));
if (!bootMatch) throw new Error('could not find the rotate bootstrap IIFE');
const afterOuter = balanceFrom(src, bootMatch.index);
let j = afterOuter;
while (src[j] === ';') j++;
const bootSrc = src.slice(bootMatch.index, j);

console.log(`array fn: ${arrayFnName} (${arrayFnSrc.length} bytes), decoder: ${decoderName}, bootstrap: ${bootSrc.length} bytes`);

const sandbox = {};
vm.createContext(sandbox);
vm.runInContext(arrayFnSrc + '\n' + decoderSrc + '\n' + bootSrc, sandbox);
const decode = (hex) => vm.runInContext(`${decoderName}(${hex})`, sandbox);

// Sanity check before trusting the decoder on the whole file.
const sample = decode('0x30e');
if (typeof sample !== 'string') throw new Error('sanity check failed: decoder did not return a string');
console.log('sanity check: decode(0x30e) ->', JSON.stringify(sample));

// Collect every local alias of the decoder, TRANSITIVELY -- aliases alias
// aliases (`const Bm9=k;` then elsewhere `const Bn0=Bm9;`). Missing this
// closure is what caused silent under-decoding the first time this was run.
const aliases = new Set([decoderName]);
let addedAny = true;
while (addedAny) {
  addedAny = false;
  const declRe = /(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*([A-Za-z_$][\w$]*)\s*[;,)]|,\s*([A-Za-z_$][\w$]*)\s*=\s*([A-Za-z_$][\w$]*)\s*[;,)]/g;
  let m;
  while ((m = declRe.exec(src))) {
    const name = m[1] || m[3];
    const rhs = m[2] || m[4];
    if (aliases.has(rhs) && !aliases.has(name)) {
      aliases.add(name);
      addedAny = true;
    }
  }
}
console.log('found', aliases.size, 'decoder aliases (transitive closure)');

const aliasPattern = [...aliases].map(a => a.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|');
const callRe = new RegExp(`\\b(${aliasPattern})\\(0x([0-9a-fA-F]+)\\)`, 'g');

let replaced = 0, failed = 0;
const failedSamples = [];
const out = src.replace(callRe, (whole, alias, hex) => {
  try {
    const val = decode('0x' + hex);
    replaced++;
    return JSON.stringify(val);
  } catch (e) {
    failed++;
    if (failedSamples.length < 10) failedSamples.push(whole);
    return whole;
  }
});

console.log('replaced', replaced, 'call sites; failed', failed);
if (failedSamples.length) console.log('failed samples:', failedSamples);

// Warn about any remaining `identifier(0xHEX)` calls so a re-run can check
// whether they're missed decoder aliases or genuinely unrelated calls (this
// bundle also has plenty of legitimate `sleep(0x64)`-style delay calls).
const leftoverRe = /\b([A-Za-z_$][\w$]{0,6})\(0x[0-9a-fA-F]+\)/g;
const leftoverNames = new Set();
let lm, leftoverCount = 0;
while ((lm = leftoverRe.exec(out))) { leftoverCount++; leftoverNames.add(lm[1]); }
console.log(`${leftoverCount} remaining identifier(0xHEX) call sites (expected: legitimate hex-literal args, e.g. ms delays) across callees:`, [...leftoverNames]);

fs.writeFileSync(outPath, out);
console.log('wrote', out.length, 'bytes to', outPath);
